name: getx_clean_base
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  get: ^4.6.1
  retrofit: ^3.0.1+1
  json_annotation: ^4.5.0
  flutter_secure_storage: ^5.0.2
  flutter_screenutil: ^5.5.2
  form_field_validator: ^1.1.0
  logger: ^1.1.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator:
  flutter_lints: ^2.0.0
  build_runner: ^2.1.10
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true

  
  assets:
   - assets/icons/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
